import type { InvestigationDatabaseSeed } from "@/stories/types";
import { CASE_003_SCHEMA } from "./schema";

const T = (h: number, m: number, s = 0) =>
  `2025-03-16 ${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;

export const CASE_003_DATABASE: InvestigationDatabaseSeed = {
  schema: CASE_003_SCHEMA,
  tables: [
    {
      name: "passengers",
      rows: [
        { passenger_id: "P001", name: "Meera Rao", age: 34, booking_class: "SUITE", status: "PERSON_OF_INTEREST" },
        { passenger_id: "P002", name: "Kabir Malhotra", age: 49, booking_class: "SUITE", status: "PERSON_OF_INTEREST" },
        { passenger_id: "P003", name: "Dev Singh", age: 44, booking_class: "STAFF", status: "PERSON_OF_INTEREST" },
        { passenger_id: "P004", name: "Nikhil Bose", age: 38, booking_class: "STAFF", status: "PERSON_OF_INTEREST" },
        { passenger_id: "P005", name: "Ananya Kapoor", age: 29, booking_class: "EXECUTIVE", status: "PERSON_OF_INTEREST" },
        { passenger_id: "P006", name: "Arvind Rao", age: 61, booking_class: "SUITE", status: "DECEASED" },
        { passenger_id: "P007", name: "Rajesh Khanna", age: 55, booking_class: "SUITE", status: "ACTIVE" },
        { passenger_id: "P008", name: "Priya Sharma", age: 42, booking_class: "SUITE", status: "ACTIVE" },
        { passenger_id: "P009", name: "Vikram Sethi", age: 38, booking_class: "EXECUTIVE", status: "ACTIVE" },
        { passenger_id: "P010", name: "Neha Gupta", age: 31, booking_class: "EXECUTIVE", status: "ACTIVE" },
        { passenger_id: "P011", name: "Sanjay Mehta", age: 47, booking_class: "FIRST", status: "ACTIVE" },
        { passenger_id: "P012", name: "Kavya Reddy", age: 28, booking_class: "FIRST", status: "ACTIVE" },
        { passenger_id: "P013", name: "Arjun Nair", age: 52, booking_class: "SUITE", status: "ACTIVE" },
        { passenger_id: "P014", name: "Divya Jain", age: 36, booking_class: "EXECUTIVE", status: "ACTIVE" },
        { passenger_id: "P015", name: "Rohit Verma", age: 45, booking_class: "FIRST", status: "ACTIVE" },
      ],
    },
    {
      name: "tickets",
      rows: [
        { ticket_id: "TK-001", passenger_id: "P001", coach: "A", cabin: "A-12", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-002", passenger_id: "P002", coach: "B", cabin: "B-04", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-003", passenger_id: "P003", coach: "A", cabin: "A-16", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 17:30:00" },
        { ticket_id: "TK-004", passenger_id: "P004", coach: "B", cabin: "B-08", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 17:15:00" },
        { ticket_id: "TK-005", passenger_id: "P005", coach: "C", cabin: "C-02", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-006", passenger_id: "P006", coach: "A", cabin: "A-17", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 17:45:00" },
        { ticket_id: "TK-007", passenger_id: "P007", coach: "A", cabin: "A-03", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-008", passenger_id: "P008", coach: "B", cabin: "B-01", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-009", passenger_id: "P009", coach: "C", cabin: "C-05", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-010", passenger_id: "P010", coach: "C", cabin: "C-08", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-011", passenger_id: "P011", coach: "C", cabin: "C-11", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-012", passenger_id: "P012", coach: "C", cabin: "C-14", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-013", passenger_id: "P013", coach: "A", cabin: "A-06", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-014", passenger_id: "P014", coach: "B", cabin: "B-10", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
        { ticket_id: "TK-015", passenger_id: "P015", coach: "C", cabin: "C-17", boarding_station: "Mumbai Central", destination: "Delhi Junction", boarding_time: "2025-03-16 18:00:00" },
      ],
    },
    {
      name: "cabin_assignments",
      rows: [
        { cabin_id: "A-17", passenger_id: "P006", assigned_from: T(17, 45), assigned_to: null, access_level: "VIP" },
        { cabin_id: "A-16", passenger_id: "P003", assigned_from: T(17, 30), assigned_to: null, access_level: "SECURITY" },
        { cabin_id: "A-12", passenger_id: "P001", assigned_from: T(18, 0), assigned_to: null, access_level: "VIP" },
        { cabin_id: "B-04", passenger_id: "P002", assigned_from: T(18, 0), assigned_to: null, access_level: "VIP" },
        { cabin_id: "B-08", passenger_id: "P004", assigned_from: T(17, 15), assigned_to: null, access_level: "STAFF" },
        { cabin_id: "C-02", passenger_id: "P005", assigned_from: T(18, 0), assigned_to: null, access_level: "GUEST" },
        { cabin_id: "A-03", passenger_id: "P007", assigned_from: T(18, 0), assigned_to: null, access_level: "VIP" },
        { cabin_id: "B-01", passenger_id: "P008", assigned_from: T(18, 0), assigned_to: null, access_level: "VIP" },
        { cabin_id: "C-05", passenger_id: "P009", assigned_from: T(18, 0), assigned_to: null, access_level: "GUEST" },
        { cabin_id: "C-08", passenger_id: "P010", assigned_from: T(18, 0), assigned_to: null, access_level: "GUEST" },
        { cabin_id: "A-06", passenger_id: "P013", assigned_from: T(18, 0), assigned_to: null, access_level: "VIP" },
        { cabin_id: "B-10", passenger_id: "P014", assigned_from: T(18, 0), assigned_to: null, access_level: "GUEST" },
      ],
    },
    {
      name: "dining_transactions",
      rows: [
        { transaction_id: "DT-001", passenger_id: "P006", timestamp: T(20, 15), location: "Dining Car", amount: 4500, item: "Chef's tasting menu" },
        { transaction_id: "DT-002", passenger_id: "P001", timestamp: T(20, 18), location: "Dining Car", amount: 3200, item: "Vegetarian thali" },
        { transaction_id: "DT-003", passenger_id: "P002", timestamp: T(20, 30), location: "Dining Car", amount: 5100, item: "Wine pairing dinner" },
        { transaction_id: "DT-004", passenger_id: "P007", timestamp: T(20, 45), location: "Dining Car", amount: 2800, item: "Mutton biryani" },
        { transaction_id: "DT-005", passenger_id: "P008", timestamp: T(20, 50), location: "Dining Car", amount: 3500, item: "Seafood platter" },
        { transaction_id: "DT-006", passenger_id: "P013", timestamp: T(21, 5), location: "Dining Car", amount: 2900, item: "Punjabi thali" },
        { transaction_id: "DT-007", passenger_id: "P006", timestamp: T(21, 30), location: "Bar Car", amount: 1800, item: "Single malt" },
        { transaction_id: "DT-008", passenger_id: "P001", timestamp: T(21, 35), location: "Bar Car", amount: 950, item: "Red wine" },
        { transaction_id: "DT-009", passenger_id: "P006", timestamp: T(23, 15), location: "Dining Car", amount: 850, item: "Late night coffee" },
        { transaction_id: "DT-010", passenger_id: "P002", timestamp: T(23, 38), location: "Service Corridor", amount: 350, item: "Room service charge" },
        { transaction_id: "DT-011", passenger_id: "P007", timestamp: T(22, 10), location: "Bar Car", amount: 1200, item: "Whiskey" },
        { transaction_id: "DT-012", passenger_id: "P008", timestamp: T(22, 20), location: "Bar Car", amount: 800, item: "Cocktail" },
        { transaction_id: "DT-013", passenger_id: "P009", timestamp: T(21, 15), location: "Dining Car", amount: 2200, item: "Pasta" },
        { transaction_id: "DT-014", passenger_id: "P010", timestamp: T(21, 45), location: "Dining Car", amount: 1800, item: "Salad and soup" },
        { transaction_id: "DT-015", passenger_id: "P011", timestamp: T(22, 0), location: "Dining Car", amount: 2600, item: "Full dinner" },
        { transaction_id: "DT-016", passenger_id: "P012", timestamp: T(22, 15), location: "Dining Car", amount: 1900, item: "Light dinner" },
        { transaction_id: "DT-017", passenger_id: "P014", timestamp: T(22, 30), location: "Bar Car", amount: 1500, item: "Wine" },
        { transaction_id: "DT-018", passenger_id: "P015", timestamp: T(22, 45), location: "Dining Car", amount: 2300, item: "Dinner" },
        { transaction_id: "DT-019", passenger_id: "P013", timestamp: T(23, 0), location: "Bar Car", amount: 900, item: "Brandy" },
      ],
    },
    {
      name: "station_logs",
      rows: [
        { log_id: "SL-001", passenger_id: "P006", station: "Mumbai Central", event_type: "BOARDING", timestamp: "2025-03-16 17:45:00" },
        { log_id: "SL-002", passenger_id: "P003", station: "Mumbai Central", event_type: "BOARDING", timestamp: "2025-03-16 17:30:00" },
        { log_id: "SL-003", passenger_id: "P001", station: "Mumbai Central", event_type: "BOARDING", timestamp: "2025-03-16 18:00:00" },
        { log_id: "SL-004", passenger_id: "P001", station: "A-12", event_type: "MOVEMENT", timestamp: T(23, 30) },
        { log_id: "SL-005", passenger_id: "P006", station: "A-17", event_type: "MOVEMENT", timestamp: T(23, 20) },
        { log_id: "SL-006", passenger_id: "P002", station: "B-04", event_type: "MOVEMENT", timestamp: T(23, 45) },
        { log_id: "SL-007", passenger_id: "P005", station: "C-02", event_type: "MOVEMENT", timestamp: T(22, 30) },
        { log_id: "SL-008", passenger_id: "P003", station: "A-16", event_type: "MOVEMENT", timestamp: T(23, 15) },
        { log_id: "SL-009", passenger_id: "P004", station: "B-08", event_type: "MOVEMENT", timestamp: T(23, 0) },
        { log_id: "SL-010", passenger_id: "P007", station: "A-03", event_type: "MOVEMENT", timestamp: T(23, 0) },
        { log_id: "SL-011", passenger_id: "P008", station: "B-01", event_type: "MOVEMENT", timestamp: T(23, 10) },
        { log_id: "SL-012", passenger_id: "P013", station: "A-06", event_type: "MOVEMENT", timestamp: T(23, 5) },
        { log_id: "SL-013", passenger_id: "P001", station: "Dining Car", event_type: "ALERT", timestamp: T(23, 20) },
        { log_id: "SL-014", passenger_id: "P006", station: "Khandala Tunnel", event_type: "ALERT", timestamp: T(23, 47) },
        { log_id: "SL-015", passenger_id: "P003", station: "Security Console", event_type: "MOVEMENT", timestamp: T(23, 46, 51) },
      ],
    },
    {
      name: "cctv_metadata",
      rows: [
        { record_id: "CC-001", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 15), event_type: "MOTION", subject_id: "P006", confidence: 0.95 },
        { record_id: "CC-002", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 20), event_type: "MOTION", subject_id: "P006", confidence: 0.92 },
        { record_id: "CC-003", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 25), event_type: "MOTION", subject_id: "P001", confidence: 0.88 },
        { record_id: "CC-004", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 30), event_type: "MOTION", subject_id: "P001", confidence: 0.91 },
        { record_id: "CC-005", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 35), event_type: "NO_MOTION", subject_id: null, confidence: 0.98 },
        { record_id: "CC-006", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 40), event_type: "NO_MOTION", subject_id: null, confidence: 0.97 },
        { record_id: "CC-007", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 45), event_type: "NO_MOTION", subject_id: null, confidence: 0.99 },
        { record_id: "CC-008", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 46), event_type: "MOTION", subject_id: "P003", confidence: 0.85 },
        { record_id: "CC-009", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 47), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.5 },
        { record_id: "CC-010", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 48), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.3 },
        { record_id: "CC-011", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 49), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.4 },
        { record_id: "CC-012", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 50), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.35 },
        { record_id: "CC-013", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 51), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.45 },
        { record_id: "CC-014", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 52), event_type: "MOTION", subject_id: null, confidence: 0.6 },
        { record_id: "CC-015", camera_id: "CAM-B-CORRIDOR", timestamp: T(23, 30), event_type: "MOTION", subject_id: "P002", confidence: 0.89 },
        { record_id: "CC-016", camera_id: "CAM-B-CORRIDOR", timestamp: T(23, 45), event_type: "MOTION", subject_id: "P002", confidence: 0.82 },
        { record_id: "CC-017", camera_id: "CAM-B-CORRIDOR", timestamp: T(23, 47), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.5 },
        { record_id: "CC-018", camera_id: "CAM-C-CORRIDOR", timestamp: T(23, 0), event_type: "MOTION", subject_id: "P005", confidence: 0.9 },
        { record_id: "CC-019", camera_id: "CAM-C-CORRIDOR", timestamp: T(23, 47), event_type: "LOW_LIGHT", subject_id: null, confidence: 0.5 },
        { record_id: "CC-020", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 54), event_type: "OVERRIDE", subject_id: "P010", confidence: 0.95 },
        { record_id: "CC-021", camera_id: "CAM-B-CORRIDOR", timestamp: T(22, 30), event_type: "MOTION", subject_id: "P007", confidence: 0.87 },
        { record_id: "CC-022", camera_id: "CAM-C-CORRIDOR", timestamp: T(22, 15), event_type: "MOTION", subject_id: "P009", confidence: 0.85 },
        { record_id: "CC-023", camera_id: "CAM-B-CORRIDOR", timestamp: T(23, 38), event_type: "MOTION", subject_id: "P002", confidence: 0.6 },
        { record_id: "CC-024", camera_id: "CAM-A-CORRIDOR", timestamp: T(23, 10), event_type: "MOTION", subject_id: "P003", confidence: 0.93 },
        { record_id: "CC-025", camera_id: "CAM-C-CORRIDOR", timestamp: T(22, 45), event_type: "MOTION", subject_id: "P012", confidence: 0.8 },
      ],
    },
    {
      name: "train_sensors",
      rows: [
        { sensor_id: "TS-001", timestamp: T(23, 40), sensor: "VIBRATION", value: "NORMAL", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-002", timestamp: T(23, 44), sensor: "VIBRATION", value: "NORMAL", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-003", timestamp: T(23, 45), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-004", timestamp: T(23, 46), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-005", timestamp: T(23, 46, 30), sensor: "ACTUATOR_STATE", value: "STANDBY", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-006", timestamp: T(23, 47), sensor: "VIBRATION", value: "TUNNEL_MODE", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-007", timestamp: T(23, 47), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-008", timestamp: T(23, 48, 16), sensor: "ACTUATOR_STATE", value: "DEPLOYED", carriage: "A", source: "MANUAL" },
        { sensor_id: "TS-009", timestamp: T(23, 48, 19), sensor: "PRESSURE", value: "SPIKE", carriage: "A", source: "MAINTENANCE" },
        { sensor_id: "TS-010", timestamp: T(23, 48, 20), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "MAINTENANCE" },
        { sensor_id: "TS-011", timestamp: T(23, 48, 21), sensor: "ACTUATOR_STATE", value: "RETRACTED", carriage: "A", source: "MANUAL" },
        { sensor_id: "TS-012", timestamp: T(23, 49), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-013", timestamp: T(23, 50), sensor: "VIBRATION", value: "TUNNEL_MODE", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-014", timestamp: T(23, 51, 12), sensor: "VIBRATION", value: "NORMAL", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-015", timestamp: T(23, 52), sensor: "PRESSURE", value: "NORMAL", carriage: "A", source: "AUTOMATIC" },
        { sensor_id: "TS-016", timestamp: T(23, 40), sensor: "TEMPERATURE", value: "22.5C", carriage: "B", source: "AUTOMATIC" },
        { sensor_id: "TS-017", timestamp: T(23, 45), sensor: "TEMPERATURE", value: "22.3C", carriage: "C", source: "AUTOMATIC" },
        { sensor_id: "TS-018", timestamp: T(23, 30), sensor: "PRESSURE", value: "NORMAL", carriage: "B", source: "AUTOMATIC" },
        { sensor_id: "TS-019", timestamp: T(23, 15), sensor: "VIBRATION", value: "NORMAL", carriage: "ENGINE", source: "AUTOMATIC" },
        { sensor_id: "TS-020", timestamp: T(23, 48, 15), sensor: "TEMPERATURE", value: "22.4C", carriage: "A", source: "AUTOMATIC" },
      ],
    },
    {
      name: "maintenance_logs",
      rows: [
        { log_id: "ML-001", timestamp: T(23, 15), engineer_id: "P004", component: "CAMERA", action: "INSPECT", carriage: "A" },
        { log_id: "ML-002", timestamp: T(23, 20), engineer_id: "P004", component: "SENSOR", action: "CALIBRATE", carriage: "B" },
        { log_id: "ML-003", timestamp: T(23, 25), engineer_id: "P004", component: "PANEL", action: "INSPECT", carriage: "C" },
        { log_id: "ML-004", timestamp: T(23, 30), engineer_id: "P004", component: "CAMERA", action: "INSPECT", carriage: "B" },
        { log_id: "ML-005", timestamp: T(23, 35), engineer_id: "P004", component: "SENSOR", action: "CALIBRATE", carriage: "C" },
        { log_id: "ML-006", timestamp: T(23, 40), engineer_id: "P004", component: "PANEL", action: "INSPECT", carriage: "A" },
        { log_id: "ML-007", timestamp: T(23, 48, 16), engineer_id: "P004", component: "ACTUATOR", action: "STATE_CHANGE", carriage: "A" },
        { log_id: "ML-008", timestamp: T(23, 55), engineer_id: "P004", component: "CAMERA", action: "INSPECT", carriage: "A" },
        { log_id: "ML-009", timestamp: T(22, 0), engineer_id: "P004", component: "SENSOR", action: "CALIBRATE", carriage: "A" },
        { log_id: "ML-010", timestamp: T(22, 30), engineer_id: "P004", component: "PANEL", action: "INSPECT", carriage: "B" },
        { log_id: "ML-011", timestamp: T(22, 45), engineer_id: "P004", component: "CAMERA", action: "REPLACE", carriage: "C" },
        { log_id: "ML-012", timestamp: T(23, 0), engineer_id: "P004", component: "SENSOR", action: "ADJUST", carriage: "ENGINE" },
        { log_id: "ML-013", timestamp: T(23, 5), engineer_id: "P004", component: "PANEL", action: "INSPECT", carriage: "A" },
        { log_id: "ML-014", timestamp: T(23, 10), engineer_id: "P004", component: "ACTUATOR", action: "INSPECT", carriage: "B" },
        { log_id: "ML-015", timestamp: T(23, 50), engineer_id: "P004", component: "SENSOR", action: "CALIBRATE", carriage: "A" },
      ],
    },
    {
      name: "access_logs",
      rows: [
        { log_id: "AL-001", timestamp: T(23, 15), credential_id: "P006-VIP", cabin_id: "A-17", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-002", timestamp: T(23, 20), credential_id: "P001-VIP", cabin_id: "A-12", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-003", timestamp: T(23, 25), credential_id: "P002-VIP", cabin_id: "B-04", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-004", timestamp: T(23, 30), credential_id: "P005-GUEST", cabin_id: "C-02", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-005", timestamp: T(23, 45), credential_id: "P006-VIP", cabin_id: "A-17", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-006", timestamp: T(23, 46, 51), credential_id: "DEV-Sec", cabin_id: "SECURITY-CONSOLE", action: "QUERY", result: "LOGGED" },
        { log_id: "AL-007", timestamp: T(23, 48), credential_id: "P006-VIP", cabin_id: "A-17", action: "UNLOCK", result: "DENIED" },
        { log_id: "AL-008", timestamp: T(23, 49), credential_id: "P003-STAFF", cabin_id: "A-17", action: "UNLOCK", result: "DENIED" },
        { log_id: "AL-009", timestamp: T(23, 50), credential_id: "P006-VIP", cabin_id: "A-17", action: "UNLOCK", result: "DENIED" },
        { log_id: "AL-010", timestamp: T(23, 54), credential_id: "ATTENDANT-01", cabin_id: "A-17", action: "OVERRIDE", result: "SUCCESS" },
        { log_id: "AL-011", timestamp: T(23, 15), credential_id: "P003-STAFF", cabin_id: "A-16", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-012", timestamp: T(23, 0), credential_id: "P007-VIP", cabin_id: "A-03", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-013", timestamp: T(23, 10), credential_id: "P008-VIP", cabin_id: "B-01", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-014", timestamp: T(23, 5), credential_id: "P013-VIP", cabin_id: "A-06", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-015", timestamp: T(22, 30), credential_id: "P005-GUEST", cabin_id: "C-02", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-016", timestamp: T(23, 38), credential_id: "P002-VIP", cabin_id: "B-04", action: "UNLOCK", result: "SUCCESS" },
        { log_id: "AL-017", timestamp: T(23, 42), credential_id: "P002-VIP", cabin_id: "B-04", action: "LOCK", result: "SUCCESS" },
        { log_id: "AL-018", timestamp: T(23, 47, 30), credential_id: "P004-STAFF", cabin_id: "B-08", action: "QUERY", result: "LOGGED" },
      ],
    },
    {
      name: "medical_report",
      rows: [
        {
          report_id: "MR-001",
          victim_id: "P006",
          estimated_window: "23:47 - 23:52",
          cause: "Single narrow puncture wound beneath left rib",
          wound_description: "Wound is consistent with a retractable mechanism, not a handheld weapon. The puncture is narrow, deep, and angular — suggesting a mechanical deployment rather than a manual stabbing motion.",
        },
      ],
    },
  ],
};
