import type { EvidenceCatalogItem } from "@/stories/types";

export const CASE_003_EVIDENCE_CATALOG: EvidenceCatalogItem[] = [
  {
    evidenceId: "EVD-001",
    name: "Arvind's Last Dining Record",
    description: "Arvind Rao's final dining transaction at 23:15 places him alive in the dining car shortly before returning to A-17.",
    category: "MOVEMENT",
    significance: "Establishes the victim was alive shortly before the tunnel.",
    source: "Dining car transaction log",
    foundTime: "2025-03-16 23:15",
    relatedEvidence: ["EVD-002"],
    accusationDimension: "identity",
  },
  {
    evidenceId: "EVD-002",
    name: "Locked Cabin — No Access",
    description: "Access logs show A-17 was locked at 23:45 and all unlock attempts during 23:47–23:52 were DENIED. Nobody entered the cabin.",
    category: "SECURITY",
    significance: "The locked-room paradox: the murder happened without cabin entry.",
    source: "Access logs",
    foundTime: "2025-03-16 23:47",
    relatedEvidence: ["EVD-003", "EVD-004"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-003",
    name: "CCTV Low-Light During Tunnel",
    description: "CCTV shows no person entering A-17 during the tunnel. Cameras switched to low-light at 23:47 and recorded no motion in A-corridor until 23:52.",
    category: "SECURITY",
    significance: "Corroborates that no one physically entered A-17 during the murder window.",
    source: "CCTV metadata",
    foundTime: "2025-03-16 23:47",
    relatedEvidence: ["EVD-002"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-004",
    name: "Suspicious Maintenance Action",
    description: "A maintenance log at 23:48:16 shows engineer P004 (Nikhil Bose) performing STATE_CHANGE on an ACTUATOR in A-coach during the tunnel window. This was not a routine inspection.",
    category: "SECURITY",
    significance: "A mechanical component was manipulated during the murder window — the weapon may have been part of the train.",
    source: "Maintenance logs",
    foundTime: "2025-03-16 23:48",
    relatedEvidence: ["EVD-005", "EVD-006"],
    accusationDimension: "supporting",
  },
  {
    evidenceId: "EVD-005",
    name: "A-17 Pressure Spike",
    description: "Train sensor at 23:48:19 recorded a PRESSURE SPIKE on A-17 service line, returning to normal at 23:48:20. The source was MAINTENANCE, not AUTOMATIC.",
    category: "SECURITY",
    significance: "An abnormal mechanical event occurred inside A-17 during the estimated death window. The spike coincides with the actuator state change.",
    source: "Train sensor logs",
    foundTime: "2025-03-16 23:48",
    relatedEvidence: ["EVD-004", "EVD-006"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-006",
    name: "Dev's Security Console Access",
    description: "Access log at 23:46:51 shows credential DEV-Sec (Dev Singh) accessing the SECURITY-CONSOLE with action QUERY, result LOGGED. Dev claims he never touched the security system.",
    category: "SECURITY",
    significance: "Directly contradicts Dev's alibi. His credential was used at the security console seconds before the tunnel entry.",
    source: "Access logs",
    foundTime: "2025-03-16 23:46",
    relatedSuspect: "P003",
    relatedEvidence: ["EVD-004", "EVD-005"],
    accusationDimension: "identity",
  },
  {
    evidenceId: "EVD-007",
    name: "Actuator Deployed and Retracted",
    description: "Train sensors show ACTUATOR_STATE changed to DEPLOYED at 23:48:16 and RETRACTED at 23:48:21. The source was MANUAL, not AUTOMATIC.",
    category: "SECURITY",
    significance: "A concealed mechanism was deployed and retracted during the murder window. The weapon was part of the train.",
    source: "Train sensor logs",
    foundTime: "2025-03-16 23:48",
    relatedEvidence: ["EVD-004", "EVD-005"],
    accusationDimension: "motive",
  },
  {
    evidenceId: "EVD-008",
    name: "Medical Report — Mechanism Wound",
    description: "The medical report describes the wound as consistent with a retractable mechanism, not a handheld weapon. The puncture is narrow, deep, and angular.",
    category: "PHYSICAL",
    significance: "Corroborates that the murder weapon was a mechanical device, not a conventional weapon brought into the cabin.",
    source: "Medical examination",
    foundTime: "2025-03-17 01:30",
    relatedEvidence: ["EVD-007"],
  },
  {
    evidenceId: "EVD-009",
    name: "Kabir's Suspicious Dining Charge",
    description: "Kabir Malhotra has a dining transaction at 23:38 in the Service Corridor — an unusual location for a passenger at that time.",
    category: "MOVEMENT",
    significance: "Red herring — places Kabir near a service area but chronology clears him of the murder.",
    source: "Dining transactions",
    foundTime: "2025-03-16 23:38",
    relatedSuspect: "P002",
  },
  {
    evidenceId: "EVD-010",
    name: "Ananya's Ticket Anomaly",
    description: "Ananya Kapoor's ticket was issued under EXECUTIVE class but her booking record shows FIRST class. A booking inconsistency.",
    category: "MOVEMENT",
    significance: "Red herring — ticket anomaly is suspicious but unrelated to the murder.",
    source: "Ticket records",
    foundTime: "2025-03-16 18:00",
    relatedSuspect: "P005",
  },
];
