import type { EvidenceCatalogItem } from "@/stories/types";

export const CASE_001_EVIDENCE_CATALOG: EvidenceCatalogItem[] = [
  {
    evidenceId: "EVD-001",
    name: "Seven-Minute Telemetry Gap",
    description: "KOSMOS-9147's telemetry record shows a gap between 02:13 and 02:21 UTC. Events that should have been logged during this period are missing.",
    category: "SECURITY",
    significance: "Proves the satellite was tampered with during a specific window. The seven minutes and forty-two seconds correspond to the unauthorized access.",
    source: "Satellite telemetry — KOSMOS-9147",
    foundTime: "2025-03-15 02:13",
    relatedEvidence: ["EVD-002", "EVD-003"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-002",
    name: "RUS-77A Authentication",
    description: "Access ID RUS-77A successfully authenticated with KOSMOS-9147 during the incident window. The credential was used multiple times, far less frequently than normal operations.",
    category: "SECURITY",
    significance: "Identifies the credential used in the breach. RUS-77A is the key to tracing who accessed the satellite.",
    source: "Satellite access logs",
    foundTime: "2025-03-15 01:58",
    relatedEvidence: ["EVD-003", "EVD-004"],
    accusationDimension: "identity",
  },
  {
    evidenceId: "EVD-003",
    name: "Sokolov's Credential Ownership",
    description: "Credential RUS-77A officially belongs to Colonel Viktor Sokolov (AGT-001). The credential was active and technically valid during the incident.",
    category: "SECURITY",
    significance: "Links the access ID to a specific person — but Sokolov's movements contradict his presence at the uplink facility.",
    source: "Credential registry",
    foundTime: "2025-03-15 01:58",
    relatedSuspect: "AGT-001",
    relatedEvidence: ["EVD-002", "EVD-004"],
    accusationDimension: "identity",
  },
  {
    evidenceId: "EVD-004",
    name: "Sokolov's Location Contradiction",
    description: "Agent movement records place Sokolov at the Moscow Secure Facility (LOC-02) during the entire incident window — hundreds of kilometers from the Plesetsk Uplink Station (LOC-01) where the satellite access originated.",
    category: "MOVEMENT",
    significance: "Proves Sokolov did not personally use RUS-77A. Someone else used his credential.",
    source: "Agent movement records",
    foundTime: "2025-03-15 02:00",
    relatedSuspect: "AGT-001",
    relatedEvidence: ["EVD-003", "EVD-005"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-005",
    name: "Anya-Dmitri Communication Pattern",
    description: "Anya Petrova (AGT-003) and Dmitri Volkov (AGT-004) communicated 8 times in the 6 hours before the incident — dramatically more than any other pair. They used an encrypted channel unusually frequently.",
    category: "COMMUNICATION",
    significance: "Establishes coordination between two suspects before the satellite breach.",
    source: "Intercepted communications",
    foundTime: "2025-03-14 20:30",
    relatedSuspect: "AGT-003",
    relatedEvidence: ["EVD-006", "EVD-007"],
    accusationDimension: "supporting",
  },
  {
    evidenceId: "EVD-006",
    name: "TR-914 Financial Pattern",
    description: "Anya Petrova received 5 separate payments tagged with reference code TR-914 totaling significant amounts. Dmitri Volkov also received 2 TR-914 payments. Individually each payment looks routine.",
    category: "FINANCIAL",
    significance: "Provides motive: someone was paid to execute the satellite operation. TR-914 connects the financial trail to the communications and evidence.",
    source: "Financial records",
    foundTime: "2025-03-13 14:00",
    relatedSuspect: "AGT-003",
    relatedEvidence: ["EVD-005", "EVD-007"],
    accusationDimension: "motive",
  },
  {
    evidenceId: "EVD-007",
    name: "TR-914 Cross-Table References",
    description: "Reference code TR-914 appears not only in financial_records but also in communications message hashes. Messages between Anya and Dmitri contain TR-914 references without mentioning the satellite by name.",
    category: "COMMUNICATION",
    significance: "Connects the financial payments to the communications. The conspirators used TR-914 as a coordination code.",
    source: "Communications intercepts + financial audit",
    foundTime: "2025-03-14 22:00",
    relatedSuspect: "AGT-003",
    relatedEvidence: ["EVD-005", "EVD-006"],
    accusationDimension: "supporting",
  },
  {
    evidenceId: "EVD-008",
    name: "Identity Trail Manipulation",
    description: "RUS-77A was used to claim 4 different identities in identity_events. This proves the identity trail was deliberately manipulated — the same credential was used by someone impersonating multiple people.",
    category: "SECURITY",
    significance: "Proves the access was not a simple credential theft. The perpetrator actively manipulated identity records to cover their trail.",
    source: "Identity verification logs",
    foundTime: "2025-03-15 02:05",
    relatedEvidence: ["EVD-002", "EVD-003"],
    accusationDimension: "supporting",
  },
  {
    evidenceId: "EVD-009",
    name: "Anya's Location at Uplink Facility",
    description: "Agent movement records show Anya Petrova arrived at the Plesetsk Uplink Station (LOC-01) at 01:30 and departed at 02:50 — covering the entire incident window. She was physically present where the satellite access originated.",
    category: "MOVEMENT",
    significance: "Places Anya at the scene of the satellite breach. Combined with the credential theft and communications, this establishes opportunity.",
    source: "Agent movement records",
    foundTime: "2025-03-15 01:30",
    relatedSuspect: "AGT-003",
    relatedEvidence: ["EVD-004", "EVD-005"],
    accusationDimension: "opportunity",
  },
  {
    evidenceId: "EVD-010",
    name: "Ethan Hunt's False Trail",
    description: "Ethan Hunt was assigned to investigate the breach but his movement records show he was at the uplink facility during the incident — despite his mission assignment placing him elsewhere. His presence was engineered to create suspicion.",
    category: "MOVEMENT",
    significance: "Reveals the larger conspiracy: the satellite breach was designed to create an intelligence incident. Ethan was deliberately inserted to cause inter-agency suspicion.",
    source: "Mission records + movement records",
    foundTime: "2025-03-15 02:00",
    relatedSuspect: "AGT-002",
    relatedEvidence: ["EVD-009"],
  },
];
